widgetTheme=widget-themes/modern
primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=false
contactMail=admin@desapega.com.br
loadingLabel=Carregando...
loginError=Erro no login
chatHeader=Fale conosco
startInfo=Por favor preencha o seguinte formulário para iniciar o chat
widgetWidth=340
widgetHeight=400
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Iníciar
backLabel=Voltar
initMessageBody=Olá, como posso ajudá-lo?
initMessageAuthor=Operador
chatInputLabel=Escreva sua duvida
timeDaysAgo=day(s) atrás
timeHoursAgo=hora(s) atrás
timeMinutesAgo=minuto(s) atrás
timeSecondsAgo=segundo(s) atrás
offlineMessage=Operador Offline
toggleSoundLabel=Efeitos de som
toggleScrollLabel=Auto- Rolar
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-Exibir
toggleFullscreenLabel=Alternar para o modo tela cheia
endChatLabel=Fim da conversa
endChatConfirmQuestion=Você tem certeza?
endChatConfirm=Sim
endChatCancel=Cancelar
contactHeader=Contate-nos
contactInfo=Todos os operadores estão off-line. Use o formulário abaixo para nos enviar um e-mail com sua pergunta.
contactNameLabel=Seu nome
contactMailLabel=Seu e-mail
contactQuestionLabel=Sua pergunta
contactSendLabel=Enviar
contactSuccessHeader=Mensagem enviada
contactSuccessMessage=Sua pergunta foi enviada. Obrigado!
contactErrorHeader=Erro
contactErrorMessage=Houve um erro ao enviar sua pergunta
headerHeight=45
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
notificationIcon=img/notification.png
