-- MySQL Script generated by MySQL Workbench
-- Thu Jan 24 18:16:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema desapega
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desapega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desapega` DEFAULT CHARACTER SET utf8 ;
USE `desapega` ;

-- -----------------------------------------------------
-- Table `desapega`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desapega`.`categoria` (
  `categoria_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `thumb` VARCHAR(255) NOT NULL,
  `status` INT(11) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desapega`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desapega`.`usuario` (
  `usuario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `tipo` INT(11) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `celular` VARCHAR(15) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(9) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `cidade_id` INT(11) NOT NULL,
  `estado_id` INT(11) NOT NULL,
  `status` INT(11) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desapega`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desapega`.`estado` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CodigoUf` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Uf` CHAR(2) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desapega`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desapega`.`municipio` (
  `municipio_id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`municipio_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
